# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nfo_pb2 as nfo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nfo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NfoLoggerStub(object):
    """--- Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogCall = channel.unary_unary(
                '/nfo.NfoLogger/LogCall',
                request_serializer=nfo__pb2.LogRequest.SerializeToString,
                response_deserializer=nfo__pb2.LogResponse.FromString,
                _registered_method=True)
        self.BatchLog = channel.unary_unary(
                '/nfo.NfoLogger/BatchLog',
                request_serializer=nfo__pb2.BatchLogRequest.SerializeToString,
                response_deserializer=nfo__pb2.BatchLogResponse.FromString,
                _registered_method=True)
        self.StreamLog = channel.stream_stream(
                '/nfo.NfoLogger/StreamLog',
                request_serializer=nfo__pb2.LogRequest.SerializeToString,
                response_deserializer=nfo__pb2.LogResponse.FromString,
                _registered_method=True)
        self.QueryLogs = channel.unary_unary(
                '/nfo.NfoLogger/QueryLogs',
                request_serializer=nfo__pb2.QueryRequest.SerializeToString,
                response_deserializer=nfo__pb2.QueryResponse.FromString,
                _registered_method=True)


class NfoLoggerServicer(object):
    """--- Service ---

    """

    def LogCall(self, request, context):
        """Log a single function call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchLog(self, request, context):
        """Log multiple entries in one round-trip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLog(self, request_iterator, context):
        """Stream log entries (high-throughput)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLogs(self, request, context):
        """Query stored logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NfoLoggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogCall': grpc.unary_unary_rpc_method_handler(
                    servicer.LogCall,
                    request_deserializer=nfo__pb2.LogRequest.FromString,
                    response_serializer=nfo__pb2.LogResponse.SerializeToString,
            ),
            'BatchLog': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchLog,
                    request_deserializer=nfo__pb2.BatchLogRequest.FromString,
                    response_serializer=nfo__pb2.BatchLogResponse.SerializeToString,
            ),
            'StreamLog': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamLog,
                    request_deserializer=nfo__pb2.LogRequest.FromString,
                    response_serializer=nfo__pb2.LogResponse.SerializeToString,
            ),
            'QueryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLogs,
                    request_deserializer=nfo__pb2.QueryRequest.FromString,
                    response_serializer=nfo__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nfo.NfoLogger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nfo.NfoLogger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NfoLogger(object):
    """--- Service ---

    """

    @staticmethod
    def LogCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nfo.NfoLogger/LogCall',
            nfo__pb2.LogRequest.SerializeToString,
            nfo__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nfo.NfoLogger/BatchLog',
            nfo__pb2.BatchLogRequest.SerializeToString,
            nfo__pb2.BatchLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLog(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nfo.NfoLogger/StreamLog',
            nfo__pb2.LogRequest.SerializeToString,
            nfo__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nfo.NfoLogger/QueryLogs',
            nfo__pb2.QueryRequest.SerializeToString,
            nfo__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
